# Generated by Django 2.1.4 on 2019-07-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, null=True)),
                ('password', models.URLField(max_length=32, null=True)),
                ('my_email', models.EmailField(db_column='email', max_length=64, null=True)),
            ],
        ),
    ]
